# 1

In [5]:
import numpy as np
#获得1到15的一维数组
a = np.arange(1, 16)
#将一维数组转变为2维数组
b = a.reshape([3,5])
#转置
c = b.T
print(c)

print()
m = [2, 4]
d = c[m]
print(d)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]

[[ 3  8 13]
 [ 5 10 15]]
